### ISSUE TITLE
Don't show user profile form if no user is selected

### ISSUE THREAD

**Issue by hettlage** [saltastroops/web-manager-2021#117]
The form for updating the user profile should not be displayed while no user is selected. This happens when the page is (re)loaded.

**Comment by mofokeng-chaka** [comment]
This issue is now addressed in the linked PR.

**Comment by hettlage** [comment]
As far as I can see, the issue is not addressed in PR #113, which I'm about to accept.

**Comment by mofokeng-chaka** [comment]
I have opened a new PR to address this issue, just minor updates from the previous one.
